<?php /** @var \Darken\Code\Runtime $this Do not edit this file. It is auto-generated and changes will be overwritten during the next compile. */ ?><?php

use Darken\Attributes\ConstructorParam;
$example = new class($this)
{
    protected \Darken\Code\Runtime $runtime;
    #[ConstructorParam]
    public string $param;
    public function __construct(\Darken\Code\Runtime $runtime)
    {
        $this->runtime = $runtime;
        $this->param = $this->runtime->getData('constructorParams', 'param');
    }
};
?>
<div style="padding: 20px; background-color: green; color:white; border-radius: 20px;">
    <?php 
echo $example->param;
?>
</div>